name: adguard-home
services:
  adguard-home:
    image: adguard/adguardhome:v0.107.38
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 53
        published: "8053"
        protocol: tcp
      - target: 53
        published: "8053"
        protocol: udp
      - target: 3000
        published: "3001"
        protocol: tcp
      - target: 853
        published: "853"
        protocol: tcp
      - target: 784
        published: "784"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/opt/adguardhome/work
        target: /opt/adguardhome/work
      - type: bind
        source: /DATA/AppData/$AppID/opt/adguardhome/conf
        target: /opt/adguardhome/conf
    x-casaos:
      ports:
        - container: "53"
          description:
            en_us: ""
        - container: "53"
          description:
            en_us: ""
        - container: "3000"
          description:
            en_us: ""
        - container: "853"
          description:
            en_us: ""
        - container: "784"
          description:
            en_us: ""
      volumes:
        - container: /opt/adguardhome/work
          description:
            en_us: ""
        - container: /opt/adguardhome/conf
          description:
            en_us: ""
    container_name: adguard-home
x-casaos:
  architectures:
    - "386"
    - amd64
    - arm
    - arm64
    - ppc64le
  main: adguard-home
  author: Mypancho.com
  category: Network
  description:
    en_us: AdGuard Home is a powerful
  developer: Adguard
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/AdGuardHome/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/AdGuardHome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/AdGuardHome/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/AdGuardHome/screenshot-3.png
  tagline:
    en_us: Securely block ads, trackers - protect your network
  thumbnail: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/AdGuardHome/thumbnail.png
  tips: {}
  title:
    en_us: AdGuard Home
  index: /
  port_map: "3001"
